/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_C_H_RPCGEN
#define _PART_C_H_RPCGEN

#include <rpc/rpc.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <ctype.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif


struct arguments {
	char *executable_path;
	int a;
	int b;
};
typedef struct arguments arguments;

#define PART_C 0x12345678
#define PART_C_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define run_binary 1
extern  char ** run_binary_1(arguments *, CLIENT *);
extern  char ** run_binary_1_svc(arguments *, struct svc_req *);
extern int part_c_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define run_binary 1
extern  char ** run_binary_1();
extern  char ** run_binary_1_svc();
extern int part_c_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arguments (XDR *, arguments*);

#else /* K&R C */
extern bool_t xdr_arguments ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_C_H_RPCGEN */
