COMPILER = gcc
ARGS = 
FILENAME = part_a

all: $(FILENAME).c
	@$(COMPILER) $(ARGS) $(FILENAME).c -o $(FILENAME).out
	@echo "Code successfully compiled."

clean:
	@rm -rf $(FILENAME).out
	@rm -rf *.txt
	@echo "Output and compiled files are successfully removed."