/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <ctype.h>
#include <string.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	char *executable_path;
	int a;
	int b;
};
typedef struct operands operands;

#define PART_B 0x12345678
#define PART_B_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define runCompiled 1
extern  char ** runcompiled_1(operands *, CLIENT *);
extern  char ** runcompiled_1_svc(operands *, struct svc_req *);
extern int part_b_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define runCompiled 1
extern  char ** runcompiled_1();
extern  char ** runcompiled_1_svc();
extern int part_b_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
